#include "main.h"
const char* prescripts[] = {
    "STARE AT A CORNER FOR EXACTLY 300 SECONDS.",    // 42字符
    "TEAR A BLANK PAGE INTO EXACTLY 17 PIECES.",     // 41字符
    "BITE YOUR LEFT INDEX FINGER UNTIL IT HURTS.",   // 43字符
    "WHISPER 'YES' TO THE NEXT PERSON WHO SPEAKS.",  // 44字符
    "POUR A GLASS OF WATER AND LET IT EVAPORATE.",   // 43字符
    "TIE A BLACK THREAD AROUND YOUR RIGHT WRIST.",   // 43字符
    "WALK BACKWARDS FOR YOUR NEXT 20 STEPS.",        // 38字符
    "APOLOGIZE TO THE NEXT DEAD INSECT YOU FIND.",   // 43字符
    "LEAVE A RUSTY COIN ON THE THIRD STAIR.",        // 38字符
    "DO NOT BLINK WHEN YOU CROSS THE NEXT DOOR.",    // 42字符
    "THROW A KEY INTO THE NEAREST RIVER.",           // 35字符
    "HOLD YOUR BREATH UNTIL YOU HEAR A SIREN." ,      // 40字符
		"FIND ISHMALE",
		"KILL YOUR PAINTING",
		"CLEAR",
		"I'm BUGRER"
};